Add ability to set individual replica count per region (#387)
* Add ability to set individual replica count per region

This changes allows a user to set different replica counts for each
target region defined with a shared_image_gallery_destination block.

Closes: https://github.com/hashicorp/packer-plugin-azure/issues/386

* Update support for shared_image_gallery_replica_count

For backwards compatibility setting shared_image_gallery_replica_count
with replication_regions, will set the replica count value for each
target region that is generated internally.

When setting replica counts using a target block the global attribute
for setting shared image gallery replica counts is not allowed.

```
~>  packer validate
example/ubuntu_managed_image_sig.targetregions.pkr.hcl
Error: 1 error(s) occurred:

* `shared_image_gallery_replica_count` can not be defined alongside
  `target_region`; you can specify the number of replicas per region
  within a single target_region block.

    on example/ubuntu_managed_image_sig.targetregions.pkr.hcl line 21:
      (source code not available)
```

* Fix replica count settings for build location

The replica count for the build location is set at the gallery level not
the target region level in the API. To ensure the replica is set
correctly, when using target_region blocks the replica count value for
the build location is updated to match the value in target_region if
set. If not set the global region count defaults to 1.

When using replicated_regions the global replica count value is set as
the value for the target region so that it matches the global count. In
this situation the replica count will be honored by all target regions.

* Fix tests broken during rebase

* Add test to for new restriction on target_region block

* Reword error message

---------

Co-authored-by: Jenna Goldstrich <jenna.goldstrich@hashicorp.com>